@echo off

echo Starting server...
start node ".\server.js"
echo Server open...

echo Starting client GUI...
start python ".\chatroom_gui.py"
echo Chat GUI running...

echo Starting node.js clients...
start node ".\client.js"
echo First node.js client started...

start node ".\client.js"
echo Second node.js client started...


echo 1 Server and 3 Clients initialized...

