@echo off

echo Starting server...
start node "C:\Users\JORDY\repo\network-application-protocol\server.js"
echo Server open...

echo Starting client GUI...
start python "C:\Users\JORDY\repo\network-application-protocol\chatroom_gui.py"
echo Chat GUI running...

echo Starting node.js clients...
start node "C:\Users\JORDY\repo\network-application-protocol\client.js"
echo First node.js client started...

start node "C:\Users\JORDY\repo\network-application-protocol\client.js"
echo Second node.js client started...


echo 1 Server and 3 Clients initialized...

